"""dark-factory#828 item (c): block `git push` from any subprocess launched
through `runner.handler_sandbox._sanitized_env()` unless `--allow-push` was
passed to the CLI.

Structural, not a runtime flag a misbehaving node could ignore: the
blocked `git` is a PATH shim placed ahead of the real one, so a coder
backend's shell cannot push without either (a) `--allow-push` being set,
or (b) deliberately hardcoding the real git's absolute path to bypass
PATH resolution — the same acceptance ceiling as any PATH-based sandbox,
noted here rather than pretended away. Real incident: a `fix` node with
full repo write+push authority pushed to a LIVE PR branch with nothing
actionable to act on.
"""

from __future__ import annotations

import os
import pathlib
import shutil
import stat
import subprocess

_SHIM_DIR = pathlib.Path.home() / ".dark-factory" / "push-guard"

# Set once at CLI startup from --allow-push (module-level, not a Context
# field — `_sanitized_env()` is called from ~8 sites with no Context in
# scope). Does NOT lift the per-subprocess shim (see `_sanitized_env`'s
# docstring) — it only gates `maybe_push_at_run_end`'s single, centralized
# push after the run has fully completed.
_ALLOW_PUSH = False

def set_allow_push(value: bool) -> None:
    """Set the process-wide --allow-push flag. Called once from
    runner/__main__.py after parsing CLI args, before any node runs."""
    global _ALLOW_PUSH
    _ALLOW_PUSH = bool(value)


def allow_push_enabled() -> bool:
    return _ALLOW_PUSH
_SHIM_NAME = "git"

_SHIM_TEMPLATE = """#!/bin/sh
# dark-factory#828 push guard — generated by runner/push_guard.py, do not edit.
# Scan ALL args, not just $1: a bare "$1 = push" check is defeated by any
# global option before the subcommand (e.g. `git -C <dir> push`, `git
# --no-pager push`) — verified live during PR review, the original $1-only
# check let `git -C <path> push` straight through to the real git. Matching
# a literal "push" token anywhere is over-inclusive (a filename literally
# named "push" on an unrelated command would also block) but that is the
# safe failure direction for a push guard: false-block, never false-allow.
# Also blocks "send-pack" — the plumbing command `git push` invokes under
# the hood to actually write objects/refs to a remote; calling it directly
# performs the exact same write and is not caught by looking for "push"
# alone. Found by an independent adversarial review pass before merge.
for arg in "$@"; do
    if [ "$arg" = "push" ] || [ "$arg" = "send-pack" ]; then
        echo "dark-factory: git push blocked by the fix-node push guard (pass --allow-push to the dark-factory CLI to enable it). See dark-factory#828." >&2
        exit 1
    fi
done
exec "{real_git}" "$@"
"""


def _write_shim(real_git: str) -> pathlib.Path:
    """Write (idempotently) the push-blocking `git` shim and return its path."""
    _SHIM_DIR.mkdir(parents=True, exist_ok=True)
    shim_path = _SHIM_DIR / _SHIM_NAME
    content = _SHIM_TEMPLATE.format(real_git=real_git)
    if not shim_path.exists() or shim_path.read_text(encoding="utf-8") != content:
        shim_path.write_text(content, encoding="utf-8")
    mode = shim_path.stat().st_mode
    shim_path.chmod(mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    return shim_path


def push_guard_env(base_env: dict[str, str]) -> dict[str, str]:
    """Return a copy of `base_env` with the push-blocking `git` shim
    prepended to PATH.

    Fails OPEN (returns `base_env` unchanged) if the real git binary
    cannot be resolved or the shim cannot be written — an observability/
    safety side-effect must never itself become a new hard failure mode
    for runs that were working before this existed. The caller
    (`_sanitized_env`) only invokes this when push is meant to be
    blocked; a resolution failure here means push is NOT blocked for that
    one subprocess, which is the safer failure direction than crashing
    every run.
    """
    real_git = shutil.which("git")
    if not real_git:
        return dict(base_env)
    try:
        shim_path = _write_shim(real_git)
    except OSError:
        return dict(base_env)
    env = dict(base_env)
    existing_path = env.get("PATH", os.defpath)
    env["PATH"] = f"{shim_path.parent}{os.pathsep}{existing_path}"
    return env


def maybe_push_at_run_end(
    workdir: "pathlib.Path | None",
    final_outcome: str,
    *,
    timeout: int = 30,
) -> dict[str, str]:
    """The ONE centralized push the runner itself may perform, at the very
    end of a run, iff `--allow-push` was set AND `final_outcome` is a
    genuine success — an ALLOWLIST (only "success" pushes), not a
    denylist of bad outcomes, so a new/renamed outcome string defaults to
    "don't push" rather than silently becoming pushable.

    dark-factory#828: the real incident's run ended `final_outcome:
    "exhausted"` — a run that never reached a real success has nothing to
    push. Uses the REAL git directly (this IS the sanctioned push path;
    it does not go through `_sanitized_env`'s shim).

    Returns an observability dict — `push_attempted`, `push_succeeded`,
    `push_skip_reason` — for the run summary/CXDB, so a caller can always
    tell whether a push happened and why one didn't.
    """
    result = {"push_attempted": "0", "push_succeeded": "0", "push_skip_reason": ""}
    if not _ALLOW_PUSH:
        result["push_skip_reason"] = "allow_push_not_set"
        return result
    normalized = str(final_outcome or "").strip().lower()
    if normalized != "success":
        result["push_skip_reason"] = f"final_outcome={normalized or 'unknown'}_is_not_success"
        return result
    if not workdir:
        result["push_skip_reason"] = "no_workdir"
        return result
    result["push_attempted"] = "1"
    try:
        proc = subprocess.run(
            ["git", "-C", str(workdir), "push"],
            capture_output=True, text=True, timeout=timeout, check=False,
            stdin=subprocess.DEVNULL,
        )
    except (OSError, subprocess.TimeoutExpired) as exc:
        result["push_skip_reason"] = f"push_error:{exc}"
        return result
    if proc.returncode == 0:
        result["push_succeeded"] = "1"
    else:
        result["push_skip_reason"] = f"push_failed_rc_{proc.returncode}:{proc.stderr.strip()[:200]}"
    return result
