#!/usr/bin/env bash
# Real Linux/systemd/AO restart-continuity canary; never a CI skip.
set -euo pipefail
fail(){ echo "FAIL: $*" >&2; exit 1; }
[ "$(uname -s)" = Linux ] || fail "Linux required"
HOSTNAME_SHORT="$(hostname -s)"; [ "${HOSTNAME_SHORT,,}" = jeff-ubuntu ] || fail "must run on jeff-ubuntu"
for c in systemctl systemd-run ao br tmux sqlite3 git sha256sum; do command -v "$c" >/dev/null || fail "missing prerequisite: $c"; done; systemd-run --help 2>&1 | grep -q -- '--setenv' || fail "systemd-run lacks --setenv"
ROOT="$(cd "$(dirname "$0")/../.." && pwd)"; INSTALLER="$ROOT/daemon/systemd/install-systemd-user.sh"
PERSIST=ai.dark-factory.daemon.service; BEFORE="$(systemctl --user is-active "$PERSIST" 2>/dev/null || true)"; persist_state(){ systemctl --user show "$PERSIST" -p ActiveState -p SubState -p MainPID -p ExecStart -p FragmentPath -p UnitFileState 2>/dev/null || true; }; PSTATE_BEFORE="$(persist_state)"
[ "$BEFORE" = inactive ] || [ "$BEFORE" = failed ] || fail "persistent unit must be stopped (was $BEFORE)"
TMP="$(mktemp -d -t df-pr755-continuity.XXXXXX)"; TOKEN="$(basename "$TMP")"; UNIT="ai.dark-factory.canary-pr755-$TOKEN.service"; BEAD=""; SID=""; BRANCH=""; WP=""; MARKER=""; BRDB=""; UNIT_DEAD=1; EVIDENCE_ROOT="${DARK_FACTORY_CONTINUITY_EVIDENCE_ROOT:-$HOME/Library/Logs/dark-factory/evidence/pr755-continuity}/$TOKEN"
save_evidence(){ mkdir -p "$EVIDENCE_ROOT" || return 1; for f in "$TMP"/pre.raw "$TMP"/post.raw "$TMP"/pre.identity "$TMP"/post.identity "$TMP"/cleanup.systemd-after "$TMP"/telemetry.jsonl "$RENDER"; do [ -f "$f" ] || continue; cp "$f" "$EVIDENCE_ROOT/$(basename "$f")" || return 1; done; (cd "$EVIDENCE_ROOT" && for f in *; do [ "$f" = SHA256SUMS ] || sha256sum -- "$f"; done >SHA256SUMS) || return 1; EVIDENCE_ROOT="$(cd "$EVIDENCE_ROOT" && pwd)"; return 0; }
cleanup(){ local ec=$? active load pid reset_ok evidence_ok=0; trap - EXIT INT TERM; if [ "$UNIT_DEAD" -eq 0 ]; then systemctl --user stop "$UNIT" >/dev/null 2>&1 || ec=1; active="$(systemctl --user is-active "$UNIT" 2>/dev/null || true)"; load="$(systemctl --user show "$UNIT" -p LoadState --value 2>/dev/null || true)"; pid="$(systemctl --user show "$UNIT" -p MainPID --value 2>/dev/null || true)"; reset_ok=1; systemctl --user reset-failed "$UNIT" >/dev/null 2>&1 || reset_ok=0; [ "$reset_ok" -eq 1 ] || [ "$load" = not-found ] || ec=1; case "$active:$load:$pid" in inactive:*:0|failed:*:0|unknown:not-found:0|unknown:not-found:) UNIT_DEAD=1;; *) UNIT_DEAD=0; ec=1;; esac; printf 'unit=%s\nstop_active=%s\nload_state=%s\nmain_pid=%s\nreset_failed_ok=%s\n' "$UNIT" "$active" "$load" "$pid" "$reset_ok" >"$TMP/cleanup.systemd-after"; fi; if [ "$UNIT_DEAD" -eq 1 ] && [ -n "$SID" ]; then ao session kill "$SID" >/dev/null 2>&1 || ec=1; [ -e "$WP" ] && { echo "FAIL: AO session kill left worktree $WP" >&2; ec=1; }; fi; [ -n "$BRDB" ] && [ -n "$BEAD" ] && br --db "$BRDB" close "$BEAD" --reason "continuity canary cleanup" >/dev/null 2>&1 || true; if [ "$(persist_state)" != "$PSTATE_BEFORE" ]; then echo "FAIL: persistent unit state drifted" >&2; ec=1; fi; for f in "$TMP"/pre.raw "$TMP"/post.raw; do [ -f "$f" ] && { echo "--- evidence: $f ---"; cat "$f"; }; done; save_evidence && evidence_ok=1 || { echo "FAIL: evidence preservation failed" >&2; ec=1; }; echo "Evidence: $EVIDENCE_ROOT"; if [ "$UNIT_DEAD" -eq 1 ] && [ "$evidence_ok" -eq 1 ]; then rm -rf "$TMP"; else echo "Temp retained: $TMP"; fi; exit "$ec"; }
trap cleanup EXIT INT TERM
SHA="c199b0b31dfc0fe04b7da262282ecc4d1f7e71f8"; [ -z "${DARK_FACTORY_EXPECTED_RELEASE_SHA:-}" ] || [ "$DARK_FACTORY_EXPECTED_RELEASE_SHA" = "$SHA" ] || fail "DARK_FACTORY_EXPECTED_RELEASE_SHA must equal reviewed release $SHA"; RENDER="$TMP/rendered.service"
DARK_FACTORY_EXPECTED_RELEASE_SHA="$SHA" "$INSTALLER" --render-only >"$RENDER" || fail "immutable release render failed"
RELEASE="$(sed -n 's/^WorkingDirectory=//p' "$RENDER")"; DAEMON="$(sed -n 's/^ExecStart=//p' "$RENDER" | awk '{print $1}')"; MODE="$(sed -n 's/^KillMode=//p' "$RENDER")"; SIGNAL="$(sed -n 's/^KillSignal=//p' "$RENDER")"
[ "$(basename "$RELEASE")" = "$SHA" ] && [ -x "$DAEMON" ] && [ -n "$MODE" ] && [ -n "$SIGNAL" ] || fail "render did not identify exact immutable release"
CFG="$TMP/daemon.toml"; cp "$RELEASE/config/daemon.toml" "$CFG" || fail "exact release config/daemon.toml missing"; for k in target_repo stage max_workers max_batch fast_tick_secs slow_tick_secs; do grep -q "^${k}[[:space:]]*=" "$CFG" || fail "release config missing $k"; done; sed -i -E 's|^target_repo = .*|target_repo = "jleechanorg/dark-factory"|; s/^stage = .*/stage = 2/; s/^max_workers = .*/max_workers = 1/; s/^max_batch = .*/max_batch = 1/; s/^fast_tick_secs = .*/fast_tick_secs = 1/; s/^slow_tick_secs = .*/slow_tick_secs = 1/' "$CFG"; sed -i '/^\[repos\."jleechanorg\/worldarchitect\.ai"\]/,/^\[repos\."jleechanorg\/dark-factory"\]/{ /^\[repos\."jleechanorg\/dark-factory"\]/!d; }' "$CFG"; mkdir -p "$TMP/worktrees"; BRDB="$TMP/.beads/beads.db"; STATE="$TMP/state"; mkdir -p "$STATE"; (cd "$TMP" && br init >/dev/null)
printf -v BODY 'target_repo: jleechanorg/dark-factory\nCanary only: create a unique dirty marker named .factory-continuity-%s in your assigned worktree, do not commit or push, and remain blocked/alive until externally stopped.\n' "$TOKEN"
BEAD="$(br --db "$BRDB" create --silent --title "PR755 continuity $TOKEN" --type task --priority 0 --labels factory --body "$BODY")"; [ -n "$BEAD" ] || fail "canary bead creation returned no ID"
systemd-run --user --unit="$UNIT" --collect -p Type=notify -p KillMode="$MODE" -p KillSignal="$SIGNAL" -p WorkingDirectory="$RELEASE" --setenv=HOME="$HOME" --setenv=DARK_FACTORY_CONFIG="$CFG" --setenv=DARK_FACTORY_STATE_DIR="$STATE" --setenv=DARK_FACTORY_TARGET_WORKTREE_ROOT="$TMP/worktrees" --setenv=DARK_FACTORY_BR_DB="$BRDB" --setenv=DARK_FACTORY_TELEMETRY_LOG="$TMP/telemetry.jsonl" -- "$DAEMON" >/dev/null; UNIT_DEAD=0
for _ in $(seq 1 90); do row="$(sqlite3 "$STATE/daemon-cxdb.sqlite" "select coalesce(session_id,''),coalesce(branch,'') from bead_overlay where bead_id='$BEAD';" 2>/dev/null || true)"; [ -n "$row" ] && [ "${row%%|*}" != "" ] && break; sleep 1; done
SID="${row%%|*}"; [ -n "$SID" ] || fail "daemon did not dispatch a real AO session"; BRANCH="${row#*|}"; [ -n "$BRANCH" ] || fail "overlay branch missing"
for _ in $(seq 1 60); do WP="$(tmux display-message -t "$SID" -p '#{pane_current_path}' 2>/dev/null || true)"; MARKER="$WP/.factory-continuity-$TOKEN"; [ -n "$WP" ] && [ -d "$WP" ] && [ -f "$MARKER" ] && break; sleep 1; done
[ -d "$WP" ] && [ -f "$MARKER" ] || fail "AO worker did not leave required dirty marker"
identity(){ local phase="${1:-pre}" path="$WP" marker="$MARKER"; if [ "$phase" = post ]; then path="$(tmux display-message -t "$SID" -p '#{pane_current_path}' 2>/dev/null || true)"; [ "$path" = "$WP" ] || fail "post-restart pane path changed: $WP -> $path"; marker="$path/.factory-continuity-$TOKEN"; [ -f "$marker" ] || fail "post-restart dirty marker missing"; fi; printf '%s\n' "$BEAD" "$(sqlite3 "$STATE/daemon-cxdb.sqlite" "select bead_id,state,session_id,branch from bead_overlay where bead_id='$BEAD';")" "$SID" "$BRANCH" "$path" "$(tmux display-message -t "$SID" -p '#{pane_pid}')" "$(sha256sum "$marker" | cut -c1-64)" "$(git -C "$path" status --porcelain=v1 | sha256sum | cut -c1-64)"; }
manifest(){ local n="$1" ao_json; ao_json="$(ao status -p dark-factory --json)" || fail "AO status failed"; printf '%s' "$ao_json" | grep -F -- "$SID" >/dev/null || fail "AO project status omitted exact session $SID"; { date -u +%FT%TZ; printf 'release=%s\n' "$SHA"; systemctl --user show "$UNIT" -p MainPID -p ExecMainStartTimestampMonotonic -p ActiveEnterTimestampMonotonic; printf 'overlay='; sqlite3 "$STATE/daemon-cxdb.sqlite" "select * from bead_overlay where bead_id='$BEAD';"; printf 'ao=%s\n' "$ao_json"; printf 'tmux='; tmux display-message -t "$SID" -p '#{session_name}|#{pane_current_path}|#{pane_pid}'; printf 'dirty='; git -C "$WP" status --porcelain=v1; printf 'marker_sha='; sha256sum "$MARKER"; } >"$TMP/$n.raw"; identity "$n" >"$TMP/$n.identity"; }
manifest pre; MAIN_BEFORE="$(systemctl --user show "$UNIT" -p MainPID --value)"; systemctl --user restart "$UNIT"; for _ in $(seq 1 30); do MAIN_AFTER="$(systemctl --user show "$UNIT" -p MainPID --value 2>/dev/null || true)"; [ -n "$MAIN_AFTER" ] && [ "$MAIN_AFTER" != 0 ] && [ "$MAIN_AFTER" != "$MAIN_BEFORE" ] && break; sleep 1; done
[ "${MAIN_AFTER:-0}" != 0 ] && [ "${MAIN_AFTER:-0}" != "$MAIN_BEFORE" ] || fail "restart did not replace daemon MainPID"; manifest post; cmp -s "$TMP/pre.identity" "$TMP/post.identity" || fail "AO/session/branch/worktree/pane/dirty identity changed across restart"; echo "PASS: exact release $SHA retained AO session $SID across transient restart"
